# content of pytest.ini
[pytest]
# Run Chrome with UI
addopts =   --headed
            --browser=chromium
            --base-url=https://www.saucedemo.com
            --tracing=retain-on-failure
            --video=retain-on-failure
            --screenshot=only-on-failure
            --reruns=0
            --reruns-delay=2
            --slowmo=1000
            --html=reports/report.html
            --alluredir=reports/allure-results
            # -m=regression
             # --numprocesses=2

testpaths = API

;markers =
;    smoke: mark a test as a smoke
;    regression: mark a test as a regression